apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: orb
      defaultBucket: orb_metrics
    secureJsonData:
      token: orb-influxdb-token
    isDefault: true
    editable: true
